apiVersion: v1
kind: Namespace
metadata:
  name: fly-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-node2
  namespace: fly-dev
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx2
          image: nginx:1.19.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx2
  name: nginx2-service
  namespace: fly-dev
spec:
  type: ClusterIP
  selector:
    app: nginx2
  ports:
    - name: nginx2
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-example-ingress
  namespace: fly-dev
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/foo"
            backend:
              service:
                name: nginx2-service
                port:
                  number: 80
