apiVersion: v1
kind: Namespace
metadata:
  name: fly-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-node
  namespace: fly-dev
  labels:
    app2: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
  namespace: fly-dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80 # service 的端口
      targetPort: 80 # port 的端口
      nodePort: 30000 # 映射的 node 端口,取值范围 30000- ? 这个值不记得了

