apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manage-service
  namespace: fly-devops
  labels:
    app: order-manage-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-manage-service
  template:
    metadata:
      labels:
        app: order-manage-service
    spec:
      containers:
        - name: order-manage-service
          image: 626246113265.dkr.ecr.us-east-2.amazonaws.com/order-manage-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-manage-service
  name: order-manage-service
  namespace: fly-devops
spec:
  type: NodePort
  selector:
    app: order-manage-service
  ports:
    - port: 8080
      targetPort: 8080 # pod 的端口
      nodePort: 30000 # 映射的 node 端口,取值范围 30000- ? 这个值不记得了

