apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx2
  name: nginx2-service
  namespace: fly-dev
spec:
  type: ClusterIP
  selector:
    app: nginx2
  ports:
    - name: nginx2
      port: 80