apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - http:
          paths:
            - pathType: Prefix
              path: /apple
              backend:
                serviceName: apple-service
                servicePort: 5678
            - pathType: Prefix
              path: /banana
              backend:
                serviceName: banana-service
                servicePort: 5678