version: '3'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: local/jenkins:latest
    container_name: jenkins-local
    user: jenkins
    ports:
      - "30901:8080"
    volumes:
      - fly-devops-jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  fly-devops-jenkins-data:
    driver: local
