apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manage-service
  namespace: fly-devops
  labels:
    app: order-manage-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-manage-service
  template:
    metadata:
      labels:
        app: order-manage-service
    spec:
      containers:
        - name: order-manage-service
          image: 626246113265.dkr.ecr.us-east-2.amazonaws.com/order-manage-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-manage-service
  name: order-manage-service
  namespace: fly-devops
spec:
  type: ClusterIP
  selector:
    app: order-manage-service
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-example-ingress
  namespace: fly-devops
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: order-manage-service
                port:
                  number: 8080
