apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-node2
  namespace: fly-dev
  labels:
    app: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx2
          image: nginx:1.19.1
          ports:
            - containerPort: 80