kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-with-jenkins
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000 # node 容器上的端口
        hostPort: 80 # 本地端口 80
  - role: worker